# Generated by Django 3.1.4 on 2021-01-02 01:31

from django.db import migrations, models
import ideas.models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='No Description', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='No Image', upload_to=ideas.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default='No Url', max_length=100),
        ),
    ]
