# Generated by Django 3.2.7 on 2021-10-03 05:31

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import projects_index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_id', models.CharField(default='930WF', max_length=5)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=projects_index.models.project_image_path)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects_index.category')),
                ('language', models.ManyToManyField(to='projects_index.Language')),
            ],
        ),
    ]
