# Generated by Django 3.1.4 on 2021-07-10 04:04

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fork',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='language',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
