# Generated by Django 3.1.4 on 2021-07-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_index', '0002_auto_20210710_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
