# Generated by Django 3.1.4 on 2021-07-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_index', '0005_auto_20210717_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
